Don't trigger ColdBox's invalid event looping protection
coldbox-modules/cbsecurity pull request #14
Opened 2020-08-16 19:17 UTC by homestar9

This is the same fix that @elpete implemented in cbGuard for an issue I reported where introducing cbSecurity or cbGuard to an app would break the `invalidEventHandler` Coldbox setting,  See here for details: https://github.com/coldbox-modules/cbguard/issues/15

2020-08-16 20:03 UTC, homestar9 commented
It looks like some of the unit tests are causing the checks to fail.  I'm not exactly sure how to address these.  My guess is that the tests themselves need to be updated to account for the new `invalidEventHandler` property in Security.cfc.  I may need some assistance in identifying what needs to be changed in order to pass all the tests.

2020-08-19 21:08 UTC, lmajano commented
So @homestar9 before I left on holiday, I had resolved an issue with this, where the invalid event handler was creating this loop.  I added a fix for it. https://github.com/ColdBox/coldbox-platform/commit/39ebe210953a026208029441c3710edff039dd91

So, can you try again WITHOUT this change. Because I tested it with it and it was working without it.

2020-08-19 21:09 UTC, lmajano commented
Just make sure you are using the BE

2020-08-19 21:12 UTC, homestar9 commented
Thanks @lmajano. I do see the change in Coldbox 6.  However, I'm having an issue with an app that still uses Coldbox 5.6.2

2020-08-24 16:26 UTC, lmajano commented
Well, no. It will only work for ColdBox 6.  So maybe, we can pivot this fix to ONLY work with ColdBox 5

2020-08-24 23:53 UTC, homestar9 commented
Okay, I have updated the pull request.  

I know in Coldbox 6 I could use something like `controller.getSystemSetting( "version" )` or `controller.getColdboxSetting( "version" )` which would spit out the version number.  However, it looks like Coldbox 5 doesn't have that.  I wound up using `controller.getColdboxSettings().version` which should work on Coldbox 5 and 6.

This does create a reliance on future versions of Coldbox supporting `getColdboxSettings()`, but that's the only way I could think of to change the fix so it would only apply to Coldbox 5.   If you know a better way, please let me know. :)

2020-09-04 13:37 UTC, lmajano commented
>I know in Coldbox 6 I could use something like controller.getSystemSetting( "version" ) or controller.getColdboxSetting( "version" ) which would spit out the version number. However, it looks like Coldbox 5 doesn't have that. I wound up using controller.getColdboxSettings().version which should work on Coldbox 5 and 6.

Perfect!!!

>This does create a reliance on future versions of Coldbox supporting getColdboxSettings(), but that's the only way I could think of to change the fix so it would only apply to Coldbox 5. If you know a better way, please let me know. :)

That's perfect as that is the getter for the entire struct and that will probably will never go away

2020-09-04 13:44 UTC, lmajano requested changes
Great job! Needs some more optimizations!

2020-09-04 13:44 UTC, lmajano commented on interceptors/Security.cfc
> +        if ( isNull( variables.onInvalidEventHandlerBean ) ) {
I think this check belongs outside of the declared function. In reality, this function should never be called if the set invalid event handler bean is never set.  This way we can shortcut it on line 232 as well.

2020-09-04 13:44 UTC, lmajano commented on interceptors/Security.cfc
> +            listGetAt( controller.getColdboxSettings().version, 1, "." ) == 5 &&
The 3 conditions are 
- is this coldbox < 6
- do we have an `onInvalidEventHandlerBean` that is not null 
- is this the invalid event handler bean.

This way the shortcuts will work and the code will be fast.

2020-09-04 13:44 UTC, lmajano commented on interceptors/Security.cfc
> +            listGetAt( controller.getColdboxSettings().version, 1, "." ) == 5 &&
Since this executes in every annotation check, this code needs to be extra fast. Therefore, evaluating the version into a list and comparing it takes time.  Do this once no prob. 50 times in a request and it adds up.

I suggest you move the ColdBox version detection to the `configure()` method and set a boolean feature flag.

```
variables.invalidHandlerCleanupEnabled = getToken( controller.getColdboxSettings().version, 1, "." ) < 6;
```

Then in your if statement, you can just do a boolean evaluation:

```
if( variables.invalidHandlerCleanupEnabled && .... )
```

2020-09-08 18:32 UTC, homestar9 commented on interceptors/Security.cfc
> +            listGetAt( controller.getColdboxSettings().version, 1, "." ) == 5 &&
I'm so glad you made the comment about performance and moving the check to `configure()`.  That was an excellent suggestion! I'll get to work on it and update the thread once complete.

2020-09-09 00:37 UTC, homestar9 commented
All set, I also moved the `!isNull( onInvalidEventHandlerBean )` to the `configure()` method as well since generally the `onInvalidEventHandler` config shouldn't change without reinitializing the app.  This should hopefully speed up performance a bit more as well.

My comments tend to be a bit verbose, so let me know if you'd like me to amend them.

2020-09-09 14:23 UTC, lmajano commented
@homestar9 perfection. Now the issue are the tests :(

2020-09-09 14:23 UTC, lmajano commented
Once the tests pass, I can merge, but you need to update them due to the changes in the source.

2020-09-09 16:50 UTC, homestar9 commented
I'm a little stumped with how to address the test changes.  The error message I'm seeing is:
`Failure: The incoming function threw exception [expression] [Component [cbsecurity.interceptors.Security] has no accessible Member with name [INVALIDEVENTHANDLER]] [] different than expected params type=[Security.ValidatorMethodException], regex=[.*]`

Is this a symptom that Wirebox isn't injecting the `invalidEventHandler` property?
`property name="invalidEventHandler" inject="coldbox:setting:invalidEventHandler";`

Or is something else trying to treat `invalidEventHandler` as a public property for some reason?

Here's an example of the unit tests that fails:
```
it( "can configure with default settings", function(){
	security.setProperties( settings );
	security
		.$( "getInstance" )
		.$args( settings.validator )
		.$results( wirebox.getInstance( settings.validator ) );
	security.configure();
	expect( security.getProperty( "rules", [] ) ).toBeEmpty();
} );
```

Another thought I had is that since this is a unit test, we may need to mock the `invalidEventHandler` property, but my mocking skills are nothing to brag about so I'm not exactly sure how to do that if indeed that is the case.  

Any tips you could provide would be very helpful!

2020-09-10 14:12 UTC, lmajano commented
Yep, you need to inject the mocks since they don't exist. Since you have defined it as a setter, you can just call it: `interceptor.setInvalidEventHandler()`. However, you also need to mock, the call to get the handler bean as well.

2020-09-13 22:02 UTC, homestar9 commented
I had to go back to section 3 on mocking from my trusty course lecture printout from CBOX-205 for this one.

The `invalidEventHandler` property doesn't need to be public so let me know if you would prefer that I make it private.

I also added 2 new unit tests that ensure the extra invalid event handler processing only occurs when the Coldbox version used is less than 6.

If you see anything that could be improved, please do let me know. :)

2020-09-14 14:56 UTC, lmajano commented
WOW! @homestar9 You have made me proud!  I can guarantee you that your coding will become faster and more solid now!  KUDOS!! 🎆 🍾 🍻

2020-09-14 14:57 UTC, merged

2020-09-14 15:29 UTC, homestar9 commented
Thank you Luis!  I hope you have a great start to your week. :)